function info(obj,varargin)

    updateTree(obj);
    typeText    = {'DECISION','STEP'};
    saveText    = {'','SAVED'};
    maxLength   = 0;
    
    fprintf('\n------------------------------\n');
    
    if nargin == 1
        fprintf('Showing info for process <a href="matlab:open %s">%s</a>.\n',func2str(obj.fHandle),func2str(obj.fHandle));
        
        for oo=1:length(obj.steps)
            maxLength   = max([maxLength length(obj.steps(oo).name)]);
        end
        for oo=1:length(obj.steps)
            if obj.steps(oo).type
                fprintf('%2i. %s<a href="matlab:%s.info(@%s)">%s</a> <a href="matlab:open %s">v%02i</a> (%8s, %8s) OUT:  %s\b\b\n',obj.steps(oo).number,...
                                                                             sprintf(repmat(' ',1,maxLength-length(obj.steps(oo).name))),...
                                                                              inputname(1),...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).version,...
                                                                              typeText{obj.steps(oo).type+1},...
                                                                              saveText{obj.steps(oo).saveme+1},...
                                                                              sprintf('%s, ',obj.steps(oo).output{:}));
            else
                fprintf('%2i. %s<a href="matlab:%s.info(@%s)">%s</a> <a href="matlab:open %s">v%02i</a> (%8s, %8s) DEC:  %s\n',obj.steps(oo).number,...
                                                                             sprintf(repmat(' ',1,maxLength-length(obj.steps(oo).name))),...
                                                                              inputname(1),...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).version,...
                                                                              typeText{obj.steps(oo).type+1},...
                                                                              saveText{obj.steps(oo).saveme+1},...
                                                                              obj.steps(oo).decide);
                
            end
        end
        
        fprintf('<a href="matlab:%s.meminfo">Show object info.</a>\n',inputname(1));
    else
        fprintf('Showing info for process <a href="matlab:open %s">%s</a>, detailed info for step %s.\n',func2str(obj.fHandle),func2str(obj.fHandle),func2str(varargin{1}));
        
        oo  = find(strcmp(func2str(varargin{1}),{obj.steps.name}));
        
        if obj.steps(oo).type
            fprintf('%2i. %s<a href="matlab:%s.info(@%s)">%s</a> <a href="matlab:open %s">v%02i</a> (%8s, %8s)\nOUT:  %s\b\b\nIN :  %s\b\b\nOPT:  %s\b\b\n',obj.steps(oo).number,...
                                                                             sprintf(repmat(' ',1,maxLength-length(obj.steps(oo).name))),...
                                                                              inputname(1),...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).version,...
                                                                              typeText{obj.steps(oo).type+1},...
                                                                              saveText{obj.steps(oo).saveme+1},...
                                                                              sprintf('%s, ',obj.steps(oo).output{:}),...
                                                                              sprintf('%s, ',obj.steps(oo).input{:}),...
                                                                              sprintf('%s, ',obj.steps(oo).optional{:}));
        else
            fprintf('%2i. %s<a href="matlab:%s.info(@%s)">%s</a> <a href="matlab:open %s">v%02i</a> (%8s, %8s)\nDEC :  %s\nBASE:  %s\b\b\nIN  :  %s\b\b\nOPT :  %s\b\b\n',obj.steps(oo).number,...
                                                                             sprintf(repmat(' ',1,maxLength-length(obj.steps(oo).name))),...
                                                                              inputname(1),...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).name,...
                                                                              obj.steps(oo).version,...
                                                                              typeText{obj.steps(oo).type+1},...
                                                                              saveText{obj.steps(oo).saveme+1},...
                                                                              obj.steps(oo).decide,...
                                                                              sprintf('%s, ',obj.steps(oo).basedon{:}),...
                                                                              sprintf('%s, ',obj.steps(oo).input{:}),...
                                                                              sprintf('%s, ',obj.steps(oo).optional{:}));
        end
                                                                      
        fprintf('<a href="matlab:%s.info">Show process info.</a>\n',inputname(1));
    end
end

