function printinputsfor(obj,output,varargin)

    updateTree(obj,output);
    
    variableName    = 'z';
    if nargin == 3
        variableName    = varargin{1};
    end
    
    printUntil  = 0;
    for oo=1:length(obj.steps)
        if any(strcmp(output,obj.steps(oo).output))
            printUntil = oo;
        end
    end
    
    if printUntil == 0
        [in,~] = strnearest(output,obj.allOutputs);
        fprintf('The output %s is not generated by process %s. Perhaps you meant either of these?\n',output,obj.process.name);
        for ii=1:length(in)
             fprintf('- <a href="matlab:%s.printinputsfor(''%s'')">%s</a>\n',inputname(1),obj.allOutputs{in(ii)},obj.allOutputs{in(ii)});
        end
    else
        
        longestInputName    = 0;
        for oo=1:printUntil
            for ii=1:length(obj.steps(oo).input)
                longestInputName = max([longestInputName length(obj.steps(oo).input{ii})]);
            end
        end
           
        longestInputName = longestInputName + 2;
        
        for oo=1:printUntil            
            for ii=1:length(obj.steps(oo).input)
                fprintf('%s.%s%s= ;\n',variableName,obj.steps(oo).input{ii},sprintf('%s',repmat(' ',1,longestInputName-length(obj.steps(oo).input{ii}))));
            end
        end
        
        fprintf('The output %s is generated by step <a href="matlab:open %s">%s</a>.\n',output,obj.steps(printUntil).name,obj.steps(printUntil).name);
    end
    
end

