function setcpdpath(obj)
    obj.priorPath   = path;
    restoredefaultpath;
    addpath('O:\Code',...
            'O:\Code\CacheProcessData5',...
            'O:\Code\data',...
            'O:\Code\functions',...
            'O:\Code\helpers',...
            'O:\Code\pilotmodels',...
            'O:\Code\processes',...
            'O:\Code\simulinkmodels',...
            'O:\Code\standardPilotModel',...
            'O:\Code\steps','-begin');
end