function p = p_curve()
    p.name      = mfilename;
    p.steps     = {@s_perceptionModelParameters,...
                   @s_makeStimulus,...
                   @s_perceptionModelInputs,...
                   @s_runPerceptionModel};
	p.branches  = {};
end