function p = p_twostagemethod()
    p.name      = mfilename;
    p.steps     = {@s_prepareModel, @s_inputSignals, @s_simulateModel, @s_prepareDataForTwoStageMethod, @s_arx_sim_pz, @d_mbic_pz_nk,...
                    @s_best_arx_model, @s_arx_modelfit_ga, @s_arx_modelfit_fmincon, @d_best_arx_modelfit_fmincon, ...
                    @s_best_arx_modelfit_fmincon};
	p.branches  = {{@s_best_arx_model, @s_arx_statistics},...
                   {@s_best_arx_model, @s_arx_vaf},...
                   {@s_inputSignals, @s_simulateModel_Te, @s_simulatePilotModel, @s_true_vaf}};
end